steps:
- uses: actions/checkout@v4

- name: Install Asciidoctor
  uses: asciidoctor/setup-asciidoctor@v1

- name: Build HTML
  run: asciidoctor Sample-AsciiDoc.adoc # Replace with your filename

- name: Deploy to GitHub Pages
  uses: peaceiris/actions-gh-pages@v3
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    publish_dir: .
